/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clueguess;

import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.Random;

/**
 *
 * @author eidur
 */
public class clientWindow extends javax.swing.JFrame {
    
        ArrayList<Carta> Sospechosos = new ArrayList<Carta>();
        ArrayList<Carta> Armas = new ArrayList<Carta>();
        ArrayList<Carta> Motivos = new ArrayList<Carta>();
        ArrayList<Carta> PCuerpo = new ArrayList<Carta>();
        ArrayList<Carta> Lugares = new ArrayList<Carta>();
        FBruta brute;
        BackT backtrack;
        Combinacion Solution;
        Combinacion PropuestaFb;
         Combinacion PropuestaBt;
    
    /**
     * Creates new form clientWindow
     */
    public clientWindow() {
        
         Sospechosos.addAll(Arrays.asList(new Carta("Colega",TCartas.TipoCarta.SOSPECHOSO, "colega.png"),new Carta("Extraño",TCartas.TipoCarta.SOSPECHOSO, "extranio.png"),new Carta("Hermanastra",TCartas.TipoCarta.SOSPECHOSO, "hermanastra.png"),new Carta("Mejor Amigo",TCartas.TipoCarta.SOSPECHOSO, "mejoramigo.png"),new Carta("Mensajero",TCartas.TipoCarta.SOSPECHOSO, "mensajero.png"),new Carta("Novia",TCartas.TipoCarta.SOSPECHOSO, "hermanastra.png"),new Carta("Vecina",TCartas.TipoCarta.SOSPECHOSO, "vecina.png")));
        Collections.shuffle(Sospechosos);
         
        Armas.addAll(Arrays.asList(new Carta("Bate",TCartas.TipoCarta.ARMA, "bate.png"),new Carta("Botella",TCartas.TipoCarta.ARMA, "botella.png"),new Carta("Cuchillo",TCartas.TipoCarta.ARMA, "cuchillo.png"),new Carta("Cuerda",TCartas.TipoCarta.ARMA, "cuerda.png"),new Carta("Machete",TCartas.TipoCarta.ARMA, "machete.png"),new Carta("Pala",TCartas.TipoCarta.ARMA, "pala.png"),new Carta("Pistola",TCartas.TipoCarta.ARMA, "pistola.png"),new Carta("Tubo",TCartas.TipoCarta.ARMA, "tubo.png")));
        Collections.shuffle(Armas);
        Motivos.addAll(Arrays.asList(new Carta("Accidente",TCartas.TipoCarta.MOTIVO, "accidente.png"),new Carta("Celos",TCartas.TipoCarta.MOTIVO, "celos.png"),new Carta("Dinero",TCartas.TipoCarta.MOTIVO, "dinero.png"),new Carta("Drogas",TCartas.TipoCarta.MOTIVO, "drogas.png"),new Carta("Venganza",TCartas.TipoCarta.MOTIVO, "venganza.png"),new Carta("Robo",TCartas.TipoCarta.MOTIVO, "robo.png")));
        Collections.shuffle(Motivos);
        PCuerpo.addAll(Arrays.asList(new Carta("Abdomen",TCartas.TipoCarta.CUERPO, "abdomen.png"),new Carta("Brazos",TCartas.TipoCarta.CUERPO, "brazos.png"),new Carta("Cabeza",TCartas.TipoCarta.CUERPO, "cabeza.png"),new Carta("Espalda",TCartas.TipoCarta.CUERPO, "espalda.png"),new Carta("Pecho",TCartas.TipoCarta.CUERPO, "pecho.png"),new Carta("Piernas",TCartas.TipoCarta.CUERPO, "piernas.png")));
        Collections.shuffle(PCuerpo);
        
        Lugares.addAll(Arrays.asList(new Carta("Balcón",TCartas.TipoCarta.LUGAR, "balcon.png"),new Carta("Baño",TCartas.TipoCarta.LUGAR, "baño.png"),new Carta("Cocina",TCartas.TipoCarta.LUGAR, "cocina.png"),new Carta("Comedor",TCartas.TipoCarta.LUGAR, "comedor.png"),new Carta("Cuarto",TCartas.TipoCarta.LUGAR, "cuarto.png"),new Carta("Garaje",TCartas.TipoCarta.LUGAR, "garaje.png"),new Carta("Patio",TCartas.TipoCarta.LUGAR, "patio.png"),new Carta("Sala",TCartas.TipoCarta.LUGAR, "sala.png"),new Carta("Terraza",TCartas.TipoCarta.LUGAR, "terraza.png")));
        Collections.shuffle(Lugares);
        
        
        
        
        initComponents();
        
        
        
    }
                                            


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        card_panel = new javax.swing.JPanel();
        MainPanel1 = new javax.swing.JPanel();
        numberVariables = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        startButton = new javax.swing.JButton();
        menuBackground = new javax.swing.JLabel();
        MainPanel2 = new javax.swing.JPanel();
        confidentialPanel = new javax.swing.JPanel();
        solutionPanel = new javax.swing.JPanel();
        solutionSuspect = new javax.swing.JLabel();
        solutionWeapon = new javax.swing.JLabel();
        solutionMotive = new javax.swing.JLabel();
        solutionBody = new javax.swing.JLabel();
        solutionRoom = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        restrictionPanel = new javax.swing.JPanel();
        scrollRestrictions = new javax.swing.JScrollPane();
        insideScrollPanel = new javax.swing.JPanel();
        individualPanel = new javax.swing.JPanel();
        restrictionToggle1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        restrictionNum = new javax.swing.JLabel();
        lblVolver = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        runLabel = new javax.swing.JLabel();
        restrictionToggle = new javax.swing.JLabel();
        respuestaTogglle = new javax.swing.JLabel();
        runtimeBT = new javax.swing.JLabel();
        runtimeFB = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        backTGuessingPanel = new javax.swing.JPanel();
        backTSuspect = new javax.swing.JLabel();
        backTWeapon = new javax.swing.JLabel();
        backTMotive = new javax.swing.JLabel();
        backTBody = new javax.swing.JLabel();
        backTRoom = new javax.swing.JLabel();
        bruteGuessingPanel = new javax.swing.JPanel();
        bruteSuspect = new javax.swing.JLabel();
        bruteWeapon = new javax.swing.JLabel();
        bruteMotive = new javax.swing.JLabel();
        bruteBody = new javax.swing.JLabel();
        bruteRoom = new javax.swing.JLabel();
        gameBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1500, 920));
        getContentPane().setLayout(new java.awt.CardLayout());

        card_panel.setLayout(new java.awt.CardLayout());

        MainPanel1.setMaximumSize(new java.awt.Dimension(1500, 920));
        MainPanel1.setMinimumSize(new java.awt.Dimension(1500, 920));
        MainPanel1.setPreferredSize(new java.awt.Dimension(1500, 920));
        MainPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        numberVariables.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        numberVariables.setText("0");
        numberVariables.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberVariablesActionPerformed(evt);
            }
        });
        MainPanel1.add(numberVariables, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 810, 50, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("N° de restricciones:");
        MainPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 800, 210, 60));

        startButton.setBackground(new java.awt.Color(0, 102, 0));
        startButton.setFont(new java.awt.Font("Cookie", 0, 24)); // NOI18N
        startButton.setForeground(new java.awt.Color(240, 240, 240));
        startButton.setText("Start");
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });
        MainPanel1.add(startButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 660, 190, 80));

        menuBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/title.png"))); // NOI18N
        MainPanel1.add(menuBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -40, -1, -1));

        card_panel.add(MainPanel1, "title");

        MainPanel2.setMaximumSize(new java.awt.Dimension(1500, 920));
        MainPanel2.setMinimumSize(new java.awt.Dimension(1500, 920));
        MainPanel2.setPreferredSize(new java.awt.Dimension(1500, 920));
        MainPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        confidentialPanel.setBackground(new java.awt.Color(189, 150, 63));
        confidentialPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(155, 107, 50)));
        confidentialPanel.setForeground(new java.awt.Color(204, 153, 0));
        confidentialPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        solutionPanel.setBackground(new java.awt.Color(0, 51, 0));
        solutionPanel.setOpaque(false);
        solutionPanel.setLayout(new java.awt.GridLayout(1, 0, 4, 5));

        solutionSuspect.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Armas/botella.png"))); // NOI18N
        solutionPanel.add(solutionSuspect);

        solutionWeapon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Armas/botella.png"))); // NOI18N
        solutionPanel.add(solutionWeapon);

        solutionMotive.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Armas/botella.png"))); // NOI18N
        solutionPanel.add(solutionMotive);

        solutionBody.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Armas/botella.png"))); // NOI18N
        solutionPanel.add(solutionBody);

        solutionRoom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Armas/botella.png"))); // NOI18N
        solutionPanel.add(solutionRoom);

        confidentialPanel.add(solutionPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, -1, 250));

        jLabel2.setFont(new java.awt.Font("Cookie", 0, 48)); // NOI18N
        jLabel2.setText("Solución Confidencial");
        confidentialPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, 340, 40));

        confidentialPanel.setVisible(false);

        MainPanel2.add(confidentialPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, 980, 450));

        restrictionPanel.setBackground(new java.awt.Color(51, 0, 0));
        restrictionPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        insideScrollPanel.setBackground(new java.awt.Color(102, 0, 0));
        insideScrollPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(240, 240, 240), 4, true));
        insideScrollPanel.setLayout(new javax.swing.BoxLayout(insideScrollPanel, javax.swing.BoxLayout.LINE_AXIS));

        individualPanel.setBackground(new java.awt.Color(0, 51, 0));
        individualPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 3, 0, 3, new java.awt.Color(240, 240, 240)));
        individualPanel.setOpaque(false);
        individualPanel.setLayout(new javax.swing.BoxLayout(individualPanel, javax.swing.BoxLayout.LINE_AXIS));
        insideScrollPanel.add(individualPanel);

        scrollRestrictions.setViewportView(insideScrollPanel);

        restrictionPanel.add(scrollRestrictions, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 820, 270));

        restrictionToggle1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/backRestriction.png"))); // NOI18N
        restrictionToggle1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                restrictionToggle1MouseClicked(evt);
            }
        });
        restrictionPanel.add(restrictionToggle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 0, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(240, 240, 240));
        jLabel5.setText("Restricciones");
        restrictionPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 220, 60));

        MainPanel2.add(restrictionPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 900, 470));
        restrictionPanel.setVisible(false);

        restrictionNum.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        restrictionNum.setForeground(new java.awt.Color(240, 240, 240));
        MainPanel2.add(restrictionNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 600, -1, -1));

        lblVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/backRestriction.png"))); // NOI18N
        lblVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblVolverMouseClicked(evt);
            }
        });
        MainPanel2.add(lblVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(1380, 10, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(240, 240, 240));
        jLabel8.setText("N° de restricciones: ");
        MainPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 600, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(240, 240, 240));
        jLabel7.setText("Backtracking");
        MainPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 440, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(240, 240, 240));
        jLabel6.setText("Fuerza Bruta");
        MainPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, -1, -1));

        runLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/run.png"))); // NOI18N
        runLabel.setText("jLabel6");
        runLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                runLabelMousePressed(evt);
            }
        });
        MainPanel2.add(runLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 20, 60, 60));

        restrictionToggle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/restriction.png"))); // NOI18N
        restrictionToggle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                restrictionToggleMouseClicked(evt);
            }
        });
        MainPanel2.add(restrictionToggle, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 10, 80, 80));

        respuestaTogglle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/solution.png"))); // NOI18N
        respuestaTogglle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                respuestaTogglleMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                respuestaTogglleMouseExited(evt);
            }
        });
        MainPanel2.add(respuestaTogglle, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 10, 123, 80));

        runtimeBT.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        runtimeBT.setForeground(new java.awt.Color(240, 240, 240));
        MainPanel2.add(runtimeBT, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 530, -1, -1));

        runtimeFB.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        runtimeFB.setForeground(new java.awt.Color(240, 240, 240));
        MainPanel2.add(runtimeFB, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 180, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setText("Tiempo de ejecución:");
        MainPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 530, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setText("Tiempo de ejecución:");
        MainPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 180, -1, -1));

        backTGuessingPanel.setBackground(new java.awt.Color(0, 51, 0));
        backTGuessingPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 0), 3));
        backTGuessingPanel.setLayout(new java.awt.GridLayout(1, 0, 4, 5));

        backTSuspect.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/default_card.png"))); // NOI18N
        backTGuessingPanel.add(backTSuspect);

        backTWeapon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/default_card.png"))); // NOI18N
        backTGuessingPanel.add(backTWeapon);

        backTMotive.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/default_card.png"))); // NOI18N
        backTGuessingPanel.add(backTMotive);

        backTBody.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/default_card.png"))); // NOI18N
        backTGuessingPanel.add(backTBody);

        backTRoom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/default_card.png"))); // NOI18N
        backTGuessingPanel.add(backTRoom);

        MainPanel2.add(backTGuessingPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 500, -1, 250));

        bruteGuessingPanel.setBackground(new java.awt.Color(0, 51, 0));
        bruteGuessingPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 0), 3));
        bruteGuessingPanel.setLayout(new java.awt.GridLayout(1, 0, 4, 5));

        bruteSuspect.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/default_card.png"))); // NOI18N
        bruteGuessingPanel.add(bruteSuspect);

        bruteWeapon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/default_card.png"))); // NOI18N
        bruteGuessingPanel.add(bruteWeapon);

        bruteMotive.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/default_card.png"))); // NOI18N
        bruteGuessingPanel.add(bruteMotive);

        bruteBody.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/default_card.png"))); // NOI18N
        bruteGuessingPanel.add(bruteBody);

        bruteRoom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/default_card.png"))); // NOI18N
        bruteGuessingPanel.add(bruteRoom);

        MainPanel2.add(bruteGuessingPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, -1, 250));

        gameBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bg.png"))); // NOI18N
        MainPanel2.add(gameBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -40, -1, -1));

        card_panel.add(MainPanel2, "algorithm");

        getContentPane().add(card_panel, "card4");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        // TODO add your handling code here:
        CardLayout escenarios = (CardLayout)card_panel.getLayout();
        escenarios.show(card_panel,"algorithm" );
        Random ran = new Random();
        this.Solution = new Combinacion(Sospechosos.get(ran.nextInt(Sospechosos.size())),Armas.get(ran.nextInt(Armas.size())),Motivos.get(ran.nextInt(Motivos.size())), PCuerpo.get(ran.nextInt(PCuerpo.size())), Lugares.get(ran.nextInt(Lugares.size())));
        SetSolution(Solution);
        this.PropuestaFb = new Combinacion(Sospechosos.get(0),Armas.get(0),Motivos.get(0), PCuerpo.get(0), Lugares.get(0));
        this.PropuestaBt = new Combinacion(Sospechosos.get(0),Armas.get(0),Motivos.get(0), PCuerpo.get(0), Lugares.get(0));
        ArrayList<javax.swing.JLabel> BruteArray = new ArrayList<javax.swing.JLabel>();
        BruteArray.addAll(Arrays.asList(this.bruteSuspect, this.bruteWeapon, this.bruteMotive, this.bruteBody, this.bruteRoom, this.runtimeFB));
        ArrayList<javax.swing.JLabel> BackTArray = new ArrayList<javax.swing.JLabel>();
        BackTArray.addAll(Arrays.asList(this.backTSuspect, this.backTWeapon, this.backTMotive, this.backTBody, this.backTRoom, this.runtimeBT));
        this.restrictionNum.setText(""+Integer.parseInt(this.numberVariables.getText()));
        
        this.brute = new FBruta(Sospechosos, Armas, Motivos, PCuerpo, Lugares, BruteArray, this.PropuestaFb, this.Solution);
        this.backtrack = new BackT(Sospechosos, Armas, Motivos, PCuerpo, Lugares, BackTArray, this.PropuestaBt, this.Solution, Integer.parseInt(this.numberVariables.getText()), this.insideScrollPanel);

        
    }//GEN-LAST:event_startButtonActionPerformed

    private void numberVariablesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberVariablesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numberVariablesActionPerformed

    private void respuestaTogglleMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_respuestaTogglleMouseEntered
        // TODO add your handling code here:
        this.confidentialPanel.setVisible(true);
    }//GEN-LAST:event_respuestaTogglleMouseEntered

    private void respuestaTogglleMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_respuestaTogglleMouseExited
        // TODO add your handling code here:
        this.confidentialPanel.setVisible(false);
    }//GEN-LAST:event_respuestaTogglleMouseExited

    private void restrictionToggleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_restrictionToggleMouseClicked
        // TODO add your handling code here:
        this.restrictionPanel.setVisible(true);
    }//GEN-LAST:event_restrictionToggleMouseClicked

    private void restrictionToggle1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_restrictionToggle1MouseClicked
        // TODO add your handling code here:
        this.restrictionPanel.setVisible(false);
    }//GEN-LAST:event_restrictionToggle1MouseClicked

    private void runLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_runLabelMousePressed
        // TODO add your handling code here:
        if(runLabel.isEnabled()){
            this.brute.start();
            this.backtrack.start();
            runLabel.setEnabled(false);
        }
    }//GEN-LAST:event_runLabelMousePressed

    private void lblVolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVolverMouseClicked
        CardLayout escenarios = (CardLayout)card_panel.getLayout();
        runLabel.setEnabled(true);
        escenarios.show(card_panel, "title");
        this.runtimeBT.setText("");
        this.runtimeFB.setText("");
        backTSuspect.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/default_card.png")));
        backTWeapon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/default_card.png")));
        backTMotive.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/default_card.png")));
        backTBody.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/default_card.png"))); 
        backTRoom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/default_card.png"))); 
        bruteSuspect.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/default_card.png"))); 
        bruteWeapon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/default_card.png")));
        bruteMotive.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/default_card.png")));
        bruteBody.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/default_card.png"))); 
        bruteRoom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/default_card.png")));
    }//GEN-LAST:event_lblVolverMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(clientWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(clientWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(clientWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(clientWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new clientWindow().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MainPanel1;
    private javax.swing.JPanel MainPanel2;
    private javax.swing.JLabel backTBody;
    private javax.swing.JPanel backTGuessingPanel;
    private javax.swing.JLabel backTMotive;
    private javax.swing.JLabel backTRoom;
    private javax.swing.JLabel backTSuspect;
    private javax.swing.JLabel backTWeapon;
    private javax.swing.JLabel bruteBody;
    private javax.swing.JPanel bruteGuessingPanel;
    private javax.swing.JLabel bruteMotive;
    private javax.swing.JLabel bruteRoom;
    private javax.swing.JLabel bruteSuspect;
    private javax.swing.JLabel bruteWeapon;
    private javax.swing.JPanel card_panel;
    private javax.swing.JPanel confidentialPanel;
    private javax.swing.JLabel gameBackground;
    private javax.swing.JPanel individualPanel;
    private javax.swing.JPanel insideScrollPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lblVolver;
    private javax.swing.JLabel menuBackground;
    private javax.swing.JTextField numberVariables;
    private javax.swing.JLabel respuestaTogglle;
    private javax.swing.JLabel restrictionNum;
    private javax.swing.JPanel restrictionPanel;
    private javax.swing.JLabel restrictionToggle;
    private javax.swing.JLabel restrictionToggle1;
    private javax.swing.JLabel runLabel;
    private javax.swing.JLabel runtimeBT;
    private javax.swing.JLabel runtimeFB;
    private javax.swing.JScrollPane scrollRestrictions;
    private javax.swing.JLabel solutionBody;
    private javax.swing.JLabel solutionMotive;
    private javax.swing.JPanel solutionPanel;
    private javax.swing.JLabel solutionRoom;
    private javax.swing.JLabel solutionSuspect;
    private javax.swing.JLabel solutionWeapon;
    private javax.swing.JButton startButton;
    // End of variables declaration//GEN-END:variables

private void SetSolution(Combinacion Solution) {                                                
        // TODO add your handling code here:
        //solutionBody.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Armas/botella.png")));
//        System.out.println(Solution.Sospechoso.Url+" "+Solution.Arma.Url+" "+Solution.Parte.Url+Solution.Motivo.Url+Solution.Lugar.Url);
        this.solutionSuspect.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Sospechosos/"+Solution.Sospechoso.Url)));
        this.solutionWeapon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Armas/"+Solution.Arma.Url)));
        this.solutionBody.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Cuerpo/"+Solution.Parte.Url)));
        this.solutionMotive.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Motivos/"+Solution.Motivo.Url)));
        this.solutionRoom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Lugares/"+Solution.Lugar.Url)));
        
    }       



}
